- name: Install armv7 and aarch64 Linkers
  if: runner.os == 'Linux'
  shell: sh
  run: |
    case "${{ join(matrix.targets) }}" in
      *aarch64*linux*musl*)
        sudo apt-get install -y gcc-aarch64-linux-gnu
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.40.3/mold-2.40.3-aarch64-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        expr "$CC" : ".*gcc" >/dev/null && : "${CFLAGS:=-std=c11 -Bmold -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration}"
        export CC
        export CFLAGS
        ;;
      *aarch64*linux*)
        sudo apt-get install -y gcc-aarch64-linux-gnu
        #sed -i -e 's|^#rustc-wrapper|rustc-wrapper|' .cargo/config.toml
        #curl -LO https://github.com/mozilla/sccache/releases/download/v0.9.0/sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz
        #tar -xvf sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz --strip=1 -C ~/.cargo/bin/
        #ls -l ~/.cargo/bin/
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.40.3/mold-2.40.3-aarch64-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        expr "$CC" : ".*gcc" >/dev/null && : "${CFLAGS:=-std=c11 -Bmold -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration}"
        export CC
        export CFLAGS
        ;;
      *arm*linux*musl*)
        sudo apt-get install -y gcc-arm-linux-gnueabihf
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.40.3/mold-2.40.3-arm-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        expr "$CC" : ".*gcc" >/dev/null && : "${CFLAGS:=-std=c11 -Bmold -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration}"
        export CC
        export CFLAGS
        ;;
      *arm*linux*)
        sudo apt-get install -y gcc-arm-linux-gnueabihf
        #sed -i -e 's|^#rustc-wrapper|rustc-wrapper|' .cargo/config.toml
        #curl -LO https://github.com/mozilla/sccache/releases/download/v0.9.0/sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz
        #tar -xvf sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz --strip=1 -C ~/.cargo/bin/
        #ls -l ~/.cargo/bin/
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.40.3/mold-2.40.3-arm-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        expr "$CC" : ".*gcc" >/dev/null && : "${CFLAGS:=-std=c11 -Bmold -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration}"
        export CC
        export CFLAGS
        ;;
      *linux*musl*)
        sudo apt-get install -y libgoogle-perftools-dev pkg-config
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.40.3/mold-2.40.3-x86_64-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        expr "$CC" : ".*gcc" >/dev/null && : "${CFLAGS:=-std=c11 -Bmold -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration}"
        export CC
        export CFLAGS
        #export CXXFLAGS
        ;;
      *linux*)
        #sed -i -e 's|^#rustc-wrapper|rustc-wrapper|' .cargo/config.toml
        sudo apt-get install -y libgoogle-perftools-dev pkg-config
        #curl -LO https://github.com/mozilla/sccache/releases/download/v0.9.0/sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz
        #tar -xvf sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz --strip=1 -C ~/.cargo/bin/
        #ls -l ~/.cargo/bin/
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.40.3/mold-2.40.3-x86_64-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        expr "$CC" : ".*gcc" >/dev/null && : "${CFLAGS:=-std=c11 -Bmold -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration}"
        export CC
        export CFLAGS
        export CXXFLAGS
        ;;
    esac

- name: "features Setting"
  id: "features"
  shell: "bash"
  run: |
    case "${{ join(matrix.targets) }}" in
      *arm*linux*musl*)
        echo "features=use-snmalloc" >> $GITHUB_OUTPUT
        #echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        # cargo-dist=cargo
        echo "cargo=cargo" >> $GITHUB_OUTPUT
        ;;
      *aarch64*linux*musl*)
        echo "features=use-snmalloc" >> $GITHUB_OUTPUT
        #echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        # cargo-dist=cargo
        echo "cargo=cargo" >> $GITHUB_OUTPUT
        ;;
      *linux*musl*)
        # x86_64 musl zigbuild is best.
        echo "features=use-snmalloc" >> $GITHUB_OUTPUT
        #echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        echo "cargo=cargo-zigbuild" >> $GITHUB_OUTPUT
        ;;
      *aarch64*linux*)
        #echo "features=use-mimalloc-rs" >> $GITHUB_OUTPUT
        echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        # cargo-dist=cargo
        echo "cargo=cargo" >> $GITHUB_OUTPUT
        ;;
      *arm*linux*)
        #echo "features=use-mimalloc-rs" >> $GITHUB_OUTPUT
        echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        # cargo-dist=cargo
        echo "cargo=cargo" >> $GITHUB_OUTPUT
        ;;
      *linux*)
        echo "features=use-snmalloc" >> $GITHUB_OUTPUT
        #echo "features=use-tcmalloc-static" >> $GITHUB_OUTPUT
        # cargo-dist=cargo
        echo "cargo=cargo-zigbuild" >> $GITHUB_OUTPUT
        #echo "cargo=cargo" >> $GITHUB_OUTPUT
        ;;
      *aarch64*windows*)
        echo "features=use-snmalloc" >> $GITHUB_OUTPUT
        #echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        echo "cargo=cargo-xwin" >> $GITHUB_OUTPUT
        ;;
      *windows*)
        echo "features=use-snmalloc" >> $GITHUB_OUTPUT
        #echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        echo "cargo=cargo-xwin" >> $GITHUB_OUTPUT
        ;;
      *)
        echo "features=use-mimalloc-rs" >> $GITHUB_OUTPUT
        #echo "features=use-auto-allocator" >> $GITHUB_OUTPUT
        # cargo-dist=cargo
        echo "cargo=cargo" >> $GITHUB_OUTPUT
        ;;
    esac
    ## backup memo
          #sed -i -e "s/features = .*/features = [\"${{ steps.features.outputs.features }}\"]/" dist-workspace.toml

- name: Install rust and rust-src
  shell: bash
  run: |
    # nightly -> rust 1.85.1 stable
    #sed -i -e 's|channel.*=.*|channel = "nightly"|' rust-toolchain.toml
    rustup target add "${{ join(matrix.targets) }}"
    rustup component add rust-src
    #rust-toolchain.tomlに記載しているので、cargoコマンドで自動で追加インストールされるため不要
    #rustup update nightly
    #rustup component add rust-src --toolchain nightly
    # 
    #sed -i -e 's|^debug|#debug|' Cargo.toml
    # copy config.toml to ~/.cargo/
    mkdir -p ~/.cargo/
    rm -f ~/.cargo/config*
    cp -f .cargo/config.toml ~/.cargo/config.toml

- name: Install dependencies cargo zigbuild
  run: |
    if [[ "${{ steps.features.outputs.cargo }}" == "cargo-zigbuild" ]];then
      sudo apt-get update
      sudo apt-get install musl-tools
      if ! command -v cargo-zigbuild > /dev/null 2>&1; then
        if ! command -v pip3 > /dev/null 2>&1; then
          dnf install --assumeyes python3-pip
          pip3 install --upgrade pip
        fi
        pip3 install cargo-zigbuild
      fi
    fi

- name: Build artifacts
  shell: "bash"
  run: |
    # Actually do builds and make zips and whatnot
    sed -i -e "s/features = .*/features = [\"${{ steps.features.outputs.features }}\"]/" dist-workspace.toml
    if [[ "${{ steps.features.outputs.cargo }}" == "cargo-zigbuild" ]];then
        dist manifest ${{ needs.plan.outputs.tag-flag }} --print=linkage --output-format=json ${{ matrix.dist_args }} > dist-manifest.json
        if [[ "${{ join(matrix.targets) }}" == "${TARGET:=$(rustc -vV | sed -n 's/^host: //p')}" ]];then
        ${{ steps.features.outputs.cargo }} zigbuild --profile dist --workspace -F ${{ steps.features.outputs.features }}
          else
        ${{ steps.features.outputs.cargo }} zigbuild --profile dist --workspace -F ${{ steps.features.outputs.features }} --target ${{ join(matrix.targets) }}
        fi
  
        mkdir -p target/distrib/dict-to-mozc-${{ join(matrix.targets) }}/
        
        cd target/distrib
        # 一時ディレクトリに展開
        #tar xf dict-to-mozc-${{ join(matrix.targets) }}.tar.xz
        # 新しい dict-to-mozc を上書きコピー
        cp -avf ../${{ join(matrix.targets) }}/dist/dict-to-mozc dict-to-mozc-${{ join(matrix.targets) }}/dict-to-mozc
        cp -avf ../../README.md dict-to-mozc-${{ join(matrix.targets) }}/
        cp -avf ../../LICENSE dict-to-mozc-${{ join(matrix.targets) }}/
        # 更新した内容で再圧縮
        tar cJf dict-to-mozc-${{ join(matrix.targets) }}.tar.xz dict-to-mozc-${{ join(matrix.targets) }}
        # check
        tar tvf dict-to-mozc-${{ join(matrix.targets) }}.tar.xz
        # sha256sum
        sha256sum dict-to-mozc-${{ join(matrix.targets) }}.tar.xz > dict-to-mozc-${{ join(matrix.targets) }}.tar.xz.sha256
        cd ../..
        dist manifest ${{ needs.plan.outputs.tag-flag }} --print=linkage --output-format=json ${{ matrix.dist_args }} > dist-manifest.json
    else
        dist build ${{ needs.plan.outputs.tag-flag }} --print=linkage --output-format=json ${{ matrix.dist_args }} > dist-manifest.json
    fi
    #-rwxr-xr-x 2 phoepsilonix phoepsilonix  1639696  2月 19 19:21 target/x86_64-unknown-linux-musl/dist/dict-to-mozc
    #-rwxr-xr-x 1 phoepsilonix phoepsilonix  1639696  2月 19 19:21 target/distrib/dict-to-mozc-x86_64-unknown-linux-musl/dict-to-mozc

    #dist build ${{ needs.plan.outputs.tag-flag }} --print=linkage --output-format=json ${{ matrix.dist_args }} > dist-manifest.json

    echo "dist ran successfully"
