- name: Install armv7 and aarch64 Linkers
  if: runner.os == 'Linux'
  shell: sh
  run: |
    case "${{ join(matrix.targets) }}" in
      *aarch64*linux*)
        sudo apt-get install gcc-aarch64-linux-gnu -y
        #sed -i -e 's|^#rustc-wrapper|rustc-wrapper|' .cargo/config.toml
        #curl -LO https://github.com/mozilla/sccache/releases/download/v0.9.0/sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz
        #tar -xvf sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz --strip=1 -C ~/.cargo/bin/
        #ls -l ~/.cargo/bin/
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.36.0/mold-2.36.0-aarch64-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        ;;
      *arm*linux*)
        sudo apt-get install gcc-arm-linux-gnueabihf -y
        #sed -i -e 's|^#rustc-wrapper|rustc-wrapper|' .cargo/config.toml
        #curl -LO https://github.com/mozilla/sccache/releases/download/v0.9.0/sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz
        #tar -xvf sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz --strip=1 -C ~/.cargo/bin/
        #ls -l ~/.cargo/bin/
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.36.0/mold-2.36.0-arm-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        ;;
      *linux*)
        #sed -i -e 's|^#rustc-wrapper|rustc-wrapper|' .cargo/config.toml
        #curl -LO https://github.com/mozilla/sccache/releases/download/v0.9.0/sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz
        #tar -xvf sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz --strip=1 -C ~/.cargo/bin/
        #ls -l ~/.cargo/bin/
        curl -Ls -o- https://github.com/rui314/mold/releases/download/v2.36.0/mold-2.36.0-x86_64-linux.tar.gz|sudo tar --strip=1 -xzf - -C/usr/local/
        hash -r
        export RUSTFLAGS="-Clink-arg=-Bmold"
        ;;
    esac

- name: Install rust and rust-src
  shell: bash
  run: |
    sed -i -e 's|channel.*=.*|channel = "nightly"|' rust-toolchain.toml
    #rust-toolchain.tomlに記載しているので、cargoコマンドで自動で追加インストールされるため不要
    #rustup update nightly
    #rustup component add rust-src --toolchain nightly
    # 
    #sed -i -e 's|^debug|#debug|' Cargo.toml
    # copy config.toml to ~/.cargo/
    mkdir -p ~/.cargo/
    rm -f ~/.cargo/config*
    cp -f .cargo/config.toml ~/.cargo/config.toml
