name: Release

# Releasesへのファイル追加のために書き込み権限が必要
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release binary
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: dict-to-mozc-x86_64-linux.tar.xz
            asset_name: dict-to-mozc-x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: dict-to-mozc-aarch64-linux.tar.xz
            asset_name: dict-to-mozc-aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: dict-to-mozc-x86_64-linux.tar.xz
            asset_name: dict-to-mozc-x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: dict-to-mozc-aarch64-linux.tar.xz
            asset_name: dict-to-mozc-aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      # SCCACHE_RECACHE: 1 # Uncomment this to clear cache, then comment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rustup cache
        run: |
          mkdir -p /home/runner/.rustup
          mkdir -p /home/runner/.cargo
          mkdir -p /home/runner/.cache

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
        with:
          version: "v0.8.2"

      - name: Get the release version from the Cargo.toml
        shell: bash
        run: echo "VERSION=$(grep -E "^version = " Cargo.toml |cut -f 3 -d" "|tr -d '"')" >> $GITHUB_ENV

      - name: Rust cache rustup
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.rustup
            /home/runner/.cargo
          key: ${{ matrix.os }}-dict-to-mozc-${{ matrix.target }}-${{ env.VERSION }}
          restore-keys: ${{ matrix.os }}-dict-to-mozc-${{ matrix.target }}-

      - name: Install stable toolchain
        run: |
          which rustup && rustup update || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y || rustup update
          echo "Running Rust program for ${{ matrix.os }}"

      - name: Cross build with all features
        run: |
          which rustc
          source $HOME/.cargo/env || $PATH=$HOME/.cargo/bin:$PATH
          which rustc
          cargo install cross
          cross build --release --target ${{ matrix.target }} --all-features --verbose --manifest-path ./Cargo.toml

      - name: Build archive
        shell: bash
        run: |
          binary_name="dict-to-mozc"

          dirname="$binary_name-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi

          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            7z a ../"$dirname.zip" "$dirname"
            7z l ../"$dirname.zip"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            tar tvf "$dirname.tar.gz"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ASSET }}
